[tool.poetry]
name = "quiz"
version = "0.1.0"
description = ""
authors = ["Saramira00 <sara.miraglia2000@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
